# Pull msql image
FROM mysql:5.6

# Maintainer
MAINTAINER Matthew Lewis <mglewis@calpoly.edu>

# Install packages
# ENV PACKAGE <package name>

# Install requirements 
RUN apt-get update && apt-get install -y wget
